import type { SQLiteDatabase } from 'expo-sqlite';

import type { PixorySpace } from '../../database/db';
import { createTimestamp } from '../../database/utils';
import { hashCompanionText, parseCompanionJsonArray, parseCompanionJsonObject } from '../companion/companionRuntimeValidation';
import type { ThoughtEventCandidate, ThoughtEventType } from './thoughtEventDetector';

export type ThoughtJobStatus = 'pending'|'running'|'retry'|'waiting_model'|'completed'|'failed'|'cancelled';
export interface ThoughtEventRecord { id:string; space:PixorySpace; roleCardId:string; threadId:string; branchRouteHash:string; lineageVersion:number; sessionKey:string; eventType:ThoughtEventType; priority:number; userMessageId:string; assistantMessageId:string; userMessageVersionHash:string; assistantMessageVersionHash:string; sourceSnapshotHash:string; evidence:Record<string,unknown>; status:'pending'|'batched'|'discarded'|'source_changed'; idempotencyKey:string; createdAt:string; updatedAt:string }
export interface ThoughtJobRecord { id:string; space:PixorySpace; roleCardId:string; threadId:string; branchRouteHash:string; lineageVersion:number; sessionKey:string; eventIds:string[]; sourceSnapshotHash:string; roleSnapshot:Record<string,unknown>; scheduledFor:string; status:ThoughtJobStatus; attemptCount:number; maxAttempts:number; quotaReservedCount:number; nextRunAt:string; leaseOwner:string|null; leaseUntil:string|null; lastErrorCode:string|null; promptTokens:number|null; completionTokens:number|null; idempotencyKey:string; createdAt:string; updatedAt:string; completedAt:string|null }
export interface ThoughtRecord { id:string; space:PixorySpace; roleCardId:string; sourceThreadId:string; sourceBranchRouteHash:string; lineageVersion:number; jobId:string; eventIds:string[]; sourceMessageIds:string[]; sourceSnapshotHash:string; priority:number; body:string; status:'active'|'stale_source'|'soft_deleted'; deliveryStatus:'pending'|'reserved'|'delivered'; reservationId:string|null; reservationMessageId:string|null; reservedAt:string|null; deliveredAt:string|null; deliveredMessageId:string|null; deletedAt:string|null; idempotencyKey:string; createdAt:string; updatedAt:string }
const str=(v:unknown)=>Array.isArray(v)?v.filter((x):x is string=>typeof x==='string'):[];
function mapEvent(r:Record<string,unknown>):ThoughtEventRecord{return{id:String(r.id),space:r.space as PixorySpace,roleCardId:String(r.roleCardId),threadId:String(r.threadId),branchRouteHash:String(r.branchRouteHash),lineageVersion:Number(r.lineageVersion),sessionKey:String(r.sessionKey),eventType:r.eventType as ThoughtEventType,priority:Number(r.priority),userMessageId:String(r.userMessageId),assistantMessageId:String(r.assistantMessageId),userMessageVersionHash:String(r.userMessageVersionHash),assistantMessageVersionHash:String(r.assistantMessageVersionHash),sourceSnapshotHash:String(r.sourceSnapshotHash),evidence:parseCompanionJsonObject(String(r.evidenceJson))??{},status:r.status as ThoughtEventRecord['status'],idempotencyKey:String(r.idempotencyKey),createdAt:String(r.createdAt),updatedAt:String(r.updatedAt)}}
function mapJob(r:Record<string,unknown>):ThoughtJobRecord{return{id:String(r.id),space:r.space as PixorySpace,roleCardId:String(r.roleCardId),threadId:String(r.threadId),branchRouteHash:String(r.branchRouteHash),lineageVersion:Number(r.lineageVersion),sessionKey:String(r.sessionKey),eventIds:str(parseCompanionJsonArray(String(r.eventIdsJson))),sourceSnapshotHash:String(r.sourceSnapshotHash),roleSnapshot:parseCompanionJsonObject(String(r.roleSnapshotJson))??{},scheduledFor:String(r.scheduledFor),status:r.status as ThoughtJobStatus,attemptCount:Number(r.attemptCount),maxAttempts:Number(r.maxAttempts),quotaReservedCount:Number(r.quotaReservedCount),nextRunAt:String(r.nextRunAt),leaseOwner:(r.leaseOwner as string|null)??null,leaseUntil:(r.leaseUntil as string|null)??null,lastErrorCode:(r.lastErrorCode as string|null)??null,promptTokens:r.promptTokens==null?null:Number(r.promptTokens),completionTokens:r.completionTokens==null?null:Number(r.completionTokens),idempotencyKey:String(r.idempotencyKey),createdAt:String(r.createdAt),updatedAt:String(r.updatedAt),completedAt:(r.completedAt as string|null)??null}}
function mapThought(r:Record<string,unknown>):ThoughtRecord{return{id:String(r.id),space:r.space as PixorySpace,roleCardId:String(r.roleCardId),sourceThreadId:String(r.sourceThreadId),sourceBranchRouteHash:String(r.sourceBranchRouteHash),lineageVersion:Number(r.lineageVersion),jobId:String(r.jobId),eventIds:str(parseCompanionJsonArray(String(r.eventIdsJson))),sourceMessageIds:str(parseCompanionJsonArray(String(r.sourceMessageIdsJson))),sourceSnapshotHash:String(r.sourceSnapshotHash),priority:Number(r.priority),body:String(r.body),status:r.status as ThoughtRecord['status'],deliveryStatus:r.deliveryStatus as ThoughtRecord['deliveryStatus'],reservationId:(r.reservationId as string|null)??null,reservationMessageId:(r.reservationMessageId as string|null)??null,reservedAt:(r.reservedAt as string|null)??null,deliveredAt:(r.deliveredAt as string|null)??null,deliveredMessageId:(r.deliveredMessageId as string|null)??null,deletedAt:(r.deletedAt as string|null)??null,idempotencyKey:String(r.idempotencyKey),createdAt:String(r.createdAt),updatedAt:String(r.updatedAt)}}

export async function recordThoughtEvents(db:SQLiteDatabase,input:{space:PixorySpace;roleCardId:string;threadId:string;branchRouteHash:string;lineageVersion:number;userMessageId:string;assistantMessageId:string;userMessageVersionHash:string;assistantMessageVersionHash:string;candidates:ThoughtEventCandidate[];now:string}):Promise<ThoughtEventRecord[]> {
  if(input.candidates.length===0)return[]; const cutoff=new Date(new Date(input.now).getTime()-10*60*1000).toISOString();
  const latest=await db.getFirstAsync<{sessionKey:string}>(`SELECT sessionKey FROM companion_thought_events WHERE space=? AND roleCardId=? AND threadId=? AND branchRouteHash=? AND lineageVersion=? AND status='pending' AND updatedAt>=? ORDER BY updatedAt DESC LIMIT 1`,input.space,input.roleCardId,input.threadId,input.branchRouteHash,input.lineageVersion,cutoff);
  const sessionKey=latest?.sessionKey??`ts_${hashCompanionText([input.space,input.roleCardId,input.threadId,input.branchRouteHash,input.now].join('\u001F')).slice(0,32)}`; const result:ThoughtEventRecord[]=[];
  for(const candidate of input.candidates){const key=[input.space,input.roleCardId,input.threadId,input.branchRouteHash,input.userMessageVersionHash,input.assistantMessageVersionHash,candidate.eventType].join('\u001F');const id=`tevt_${hashCompanionText(key).slice(0,32)}`;const sourceSnapshotHash=hashCompanionText([input.userMessageId,input.userMessageVersionHash,input.assistantMessageId,input.assistantMessageVersionHash].join('\u001F'));await db.runAsync(`INSERT OR IGNORE INTO companion_thought_events (id,space,roleCardId,threadId,branchRouteHash,lineageVersion,sessionKey,eventType,priority,userMessageId,assistantMessageId,userMessageVersionHash,assistantMessageVersionHash,sourceSnapshotHash,evidenceJson,status,idempotencyKey,createdAt,updatedAt) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,'pending',?,?,?)`,id,input.space,input.roleCardId,input.threadId,input.branchRouteHash,input.lineageVersion,sessionKey,candidate.eventType,candidate.priority,input.userMessageId,input.assistantMessageId,input.userMessageVersionHash,input.assistantMessageVersionHash,sourceSnapshotHash,JSON.stringify(candidate.evidence),key,input.now,input.now);const row=await db.getFirstAsync<Record<string,unknown>>('SELECT * FROM companion_thought_events WHERE idempotencyKey=?',key);if(row)result.push(mapEvent(row));}
  return result;
}
export async function listThoughtEvents(db:SQLiteDatabase,ids:string[]):Promise<ThoughtEventRecord[]>{if(!ids.length)return[];const rows=await db.getAllAsync<Record<string,unknown>>(`SELECT * FROM companion_thought_events WHERE id IN (${ids.map(()=>'?').join(',')})`,...ids);return rows.map(mapEvent)}
export async function settleThoughtSession(db:SQLiteDatabase,input:{space:PixorySpace;roleCardId:string;threadId:string;branchRouteHash:string;lineageVersion:number;sessionKey:string;roleSnapshot:Record<string,unknown>;now:string}):Promise<ThoughtJobRecord|null>{const events=(await db.getAllAsync<Record<string,unknown>>(`SELECT * FROM companion_thought_events WHERE space=? AND roleCardId=? AND threadId=? AND branchRouteHash=? AND lineageVersion=? AND sessionKey=? AND status='pending' ORDER BY priority DESC,createdAt ASC`,input.space,input.roleCardId,input.threadId,input.branchRouteHash,input.lineageVersion,input.sessionKey)).map(mapEvent);if(!events.length)return null;const eventIds=events.map(e=>e.id);const sourceSnapshotHash=hashCompanionText(events.map(e=>`${e.id}:${e.sourceSnapshotHash}`).join('\u001F'));const key=`thought-job:${input.space}:${input.roleCardId}:${input.threadId}:${input.branchRouteHash}:${input.sessionKey}`;const id=`tjob_${hashCompanionText(key).slice(0,32)}`;await db.runAsync(`INSERT OR IGNORE INTO companion_thought_jobs (id,space,roleCardId,threadId,branchRouteHash,lineageVersion,sessionKey,eventIdsJson,sourceSnapshotHash,roleSnapshotJson,scheduledFor,status,nextRunAt,idempotencyKey,createdAt,updatedAt) VALUES(?,?,?,?,?,?,?,?,?,?,?,'pending',?,?,?,?)`,id,input.space,input.roleCardId,input.threadId,input.branchRouteHash,input.lineageVersion,input.sessionKey,JSON.stringify(eventIds),sourceSnapshotHash,JSON.stringify(input.roleSnapshot),input.now,input.now,key,input.now,input.now);await db.runAsync(`UPDATE companion_thought_events SET status='batched',updatedAt=? WHERE id IN (${eventIds.map(()=>'?').join(',')}) AND status='pending'`,input.now,...eventIds);return findThoughtJob(db,id)}
export async function findThoughtJob(db:SQLiteDatabase,id:string):Promise<ThoughtJobRecord|null>{const r=await db.getFirstAsync<Record<string,unknown>>('SELECT * FROM companion_thought_jobs WHERE id=?',id);return r?mapJob(r):null}
export async function listReadyThoughtJobs(db:SQLiteDatabase,input:{space:PixorySpace;now:string;limit?:number}):Promise<ThoughtJobRecord[]>{const rows=await db.getAllAsync<Record<string,unknown>>(`SELECT * FROM companion_thought_jobs WHERE space=? AND nextRunAt<=? AND (status IN ('pending','retry','waiting_model') OR (status='running' AND (leaseUntil IS NULL OR leaseUntil<=?))) ORDER BY nextRunAt,createdAt LIMIT ?`,input.space,input.now,input.now,Math.max(1,Math.min(10,input.limit??1)));return rows.map(mapJob)}
export async function acquireThoughtJob(db:SQLiteDatabase,input:{id:string;workerId:string;now:string;leaseUntil:string}):Promise<ThoughtJobRecord|null>{await db.runAsync(`UPDATE companion_thought_jobs SET status='running',leaseOwner=?,leaseUntil=?,attemptCount=attemptCount+1,updatedAt=? WHERE id=? AND (status IN ('pending','retry','waiting_model') OR (status='running' AND (leaseUntil IS NULL OR leaseUntil<=?)))`,input.workerId,input.leaseUntil,input.now,input.id,input.now);const j=await findThoughtJob(db,input.id);return j?.status==='running'&&j.leaseOwner===input.workerId?j:null}
function beijingBounds(now:string){const parts=new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Shanghai',year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(new Date(now));const value=(t:string)=>parts.find(p=>p.type===t)?.value??'00';const date=`${value('year')}-${value('month')}-${value('day')}`;const start=new Date(`${date}T00:00:00+08:00`);return{start:start.toISOString(),end:new Date(start.getTime()+24*60*60*1000).toISOString()}}
export async function reserveThoughtQuota(db:SQLiteDatabase,job:ThoughtJobRecord,requested:number,now:string):Promise<number>{if(job.quotaReservedCount>0)return job.quotaReservedCount;const bounds=beijingBounds(now);await db.runAsync(`UPDATE companion_thought_jobs SET quotaReservedCount=MIN(?,MAX(0,3-(SELECT COUNT(*) FROM companion_thoughts WHERE space=? AND roleCardId=? AND createdAt>=? AND createdAt<?)-(SELECT COALESCE(SUM(quotaReservedCount),0) FROM companion_thought_jobs WHERE space=? AND roleCardId=? AND id!=? AND status IN ('running','retry','waiting_model')))),updatedAt=? WHERE id=? AND leaseOwner=? AND quotaReservedCount=0`,Math.max(0,requested),job.space,job.roleCardId,bounds.start,bounds.end,job.space,job.roleCardId,job.id,now,job.id,job.leaseOwner);const current=await findThoughtJob(db,job.id);return current?.leaseOwner===job.leaseOwner?current.quotaReservedCount:0}
export async function transitionThoughtJob(db:SQLiteDatabase,input:{id:string;workerId:string;status:ThoughtJobStatus;now:string;nextRunAt?:string;errorCode?:string|null;releaseQuota?:boolean}):Promise<void>{await db.runAsync(`UPDATE companion_thought_jobs SET status=?,nextRunAt=COALESCE(?,nextRunAt),lastErrorCode=?,quotaReservedCount=CASE WHEN ? THEN 0 ELSE quotaReservedCount END,leaseOwner=NULL,leaseUntil=NULL,completedAt=CASE WHEN ? IN ('completed','failed','cancelled') THEN ? ELSE completedAt END,updatedAt=? WHERE id=? AND leaseOwner=?`,input.status,input.nextRunAt??null,input.errorCode??null,input.releaseQuota?1:0,input.status,input.now,input.now,input.id,input.workerId)}
export async function recordThoughtJobUsage(db:SQLiteDatabase,input:{id:string;promptTokens:number|null;completionTokens:number|null;now:string}):Promise<void>{if(input.promptTokens==null&&input.completionTokens==null)return;await db.runAsync(`UPDATE companion_thought_jobs SET promptTokens=COALESCE(?,promptTokens),completionTokens=COALESCE(?,completionTokens),updatedAt=? WHERE id=?`,input.promptTokens,input.completionTokens,input.now,input.id)}
export async function completeThoughtJob(db:SQLiteDatabase,input:{job:ThoughtJobRecord;workerId:string;items:Array<{eventType:ThoughtEventType;sourceMessageIds:string[];priority:number;body:string}>;now:string}):Promise<ThoughtRecord[]>{const current=await findThoughtJob(db,input.job.id);if(!current||current.status!=='running'||current.leaseOwner!==input.workerId||input.items.length>current.quotaReservedCount)return[];const events=await listThoughtEvents(db,current.eventIds);const output:ThoughtRecord[]=[];for(const item of input.items){const key=[current.id,item.eventType,item.sourceMessageIds.join(','),hashCompanionText(item.body)].join('\u001F');const id=`thought_${hashCompanionText(key).slice(0,32)}`;const sourceIds=new Set(item.sourceMessageIds);const matchedEvents=events.filter(event=>event.eventType===item.eventType&&(sourceIds.has(event.userMessageId)||sourceIds.has(event.assistantMessageId)));if(matchedEvents.length===0)continue;const eventIds=matchedEvents.map(event=>event.id);const canonicalSourceMessageIds=[...new Set(matchedEvents.flatMap(event=>[event.userMessageId,event.assistantMessageId]))];await db.runAsync(`INSERT OR IGNORE INTO companion_thoughts (id,space,roleCardId,sourceThreadId,sourceBranchRouteHash,lineageVersion,jobId,eventIdsJson,sourceMessageIdsJson,sourceSnapshotHash,priority,body,status,deliveryStatus,idempotencyKey,createdAt,updatedAt) VALUES(?,?,?,?,?,?,?,?,?,?,?,?, 'active','pending',?,?,?)`,id,current.space,current.roleCardId,current.threadId,current.branchRouteHash,current.lineageVersion,current.id,JSON.stringify(eventIds),JSON.stringify(canonicalSourceMessageIds),current.sourceSnapshotHash,item.priority,item.body,key,input.now,input.now);const row=await db.getFirstAsync<Record<string,unknown>>('SELECT * FROM companion_thoughts WHERE idempotencyKey=?',key);if(row)output.push(mapThought(row));}await transitionThoughtJob(db,{id:current.id,workerId:input.workerId,status:'completed',now:input.now,releaseQuota:true});return output}
export async function listThoughtsForRole(db:SQLiteDatabase,roleCardId:string,includeDeleted=false):Promise<ThoughtRecord[]>{return(await db.getAllAsync<Record<string,unknown>>(`SELECT * FROM companion_thoughts WHERE roleCardId=? AND status IN (${includeDeleted?"'active','soft_deleted'":"'active'"}) ORDER BY createdAt DESC`,roleCardId)).map(mapThought)}
export async function softDeleteThought(db:SQLiteDatabase,id:string):Promise<void>{const now=createTimestamp();await db.runAsync(`UPDATE companion_thoughts SET status='soft_deleted',deliveryStatus=CASE WHEN deliveryStatus='reserved' THEN 'pending' ELSE deliveryStatus END,reservationId=NULL,reservationMessageId=NULL,reservedAt=NULL,deletedAt=?,updatedAt=? WHERE id=? AND status='active'`,now,now,id)}
export async function restoreThought(db:SQLiteDatabase,id:string):Promise<void>{await db.runAsync(`UPDATE companion_thoughts SET status='active',deletedAt=NULL,updatedAt=? WHERE id=? AND status='soft_deleted'`,createTimestamp(),id)}
export async function permanentlyDeleteThought(db:SQLiteDatabase,id:string):Promise<void>{await db.runAsync('DELETE FROM companion_thoughts WHERE id=?',id)}
export async function permanentlyDeleteThoughts(db:SQLiteDatabase,ids:string[]):Promise<number>{
  const uniqueIds=[...new Set(ids)];
  if(uniqueIds.length===0||uniqueIds.length!==ids.length)throw new Error('所选独白已发生变化，请刷新后重试。');
  const placeholders=uniqueIds.map(()=>'?').join(', ');
  let deletedCount=0;
  await db.withExclusiveTransactionAsync(async(txn)=>{
    const selected=await txn.getAllAsync<{id:string}>(`SELECT id FROM companion_thoughts WHERE id IN (${placeholders})`,...uniqueIds);
    if(selected.length!==uniqueIds.length)throw new Error('所选独白已发生变化，请刷新后重试。');
    const deletion=await txn.runAsync(`DELETE FROM companion_thoughts WHERE id IN (${placeholders})`,...uniqueIds);
    deletedCount=Number(deletion.changes??0);
    if(deletedCount!==uniqueIds.length)throw new Error('所选独白已发生变化，请刷新后重试。');
  });
  return deletedCount;
}
export const thoughtRepository={acquireJob:acquireThoughtJob,completeJob:completeThoughtJob,findJob:findThoughtJob,listEvents:listThoughtEvents,listForRole:listThoughtsForRole,listReadyJobs:listReadyThoughtJobs,permanentlyDelete:permanentlyDeleteThought,permanentlyDeleteMany:permanentlyDeleteThoughts,recordEvents:recordThoughtEvents,recordUsage:recordThoughtJobUsage,reserveQuota:reserveThoughtQuota,restore:restoreThought,settleSession:settleThoughtSession,softDelete:softDeleteThought,transitionJob:transitionThoughtJob};
