import type { SQLiteDatabase } from 'expo-sqlite';

import { aiRoleCardRepository, aiThreadRepository, runWithDatabaseSpace, type PixorySpace } from '../../database';
import type { AiMessageRecord } from '../../database/repositories/aiThreadRepository';
import type { AiThreadRecord } from '../types';
import { hashBranchRoute } from '../context/conversationCoverage';
import { hashCompanionMessageVersion } from '../companion/companionRuntimeValidation';
import { detectThoughtEvents } from './thoughtEventDetector';
import { thoughtRepository } from './thoughtRepository';

interface ActiveThoughtSession { space:PixorySpace;roleCardId:string;threadId:string;branchRouteHash:string;lineageVersion:number;sessionKey:string;roleSnapshot:Record<string,unknown> }
const timers=new Map<string,ReturnType<typeof setTimeout>>(); const activeBySpace=new Map<PixorySpace,ActiveThoughtSession>();
const settlingBySpace=new Map<PixorySpace,Set<Promise<unknown>>>();const suspendedSpaces=new Set<PixorySpace>(['personal']);
const key=(s:ActiveThoughtSession)=>`${s.space}:${s.roleCardId}:${s.threadId}:${s.branchRouteHash}:${s.sessionKey}`;
function messageHash(m:AiMessageRecord){return hashCompanionMessageVersion({branchRootMessageId:m.branchRootMessageId,branchVersionIndex:m.branchVersionIndex,completedAt:m.completedAt,content:m.content,id:m.id,role:m.role,status:m.status,updatedAt:m.updatedAt})}
async function performSettle(session:ActiveThoughtSession,now=new Date().toISOString()) {if(suspendedSpaces.has(session.space))return null;const job=await runWithDatabaseSpace(session.space,db=>thoughtRepository.settleSession(db,{...session,now}));if(suspendedSpaces.has(session.space))return job;if(job){const {scheduleCompanionMaintenance}=await import('../companion/companionMaintenanceQueue');scheduleCompanionMaintenance({delayMs:0,space:session.space});}timers.delete(key(session));if(activeBySpace.get(session.space)&&key(activeBySpace.get(session.space)!)===key(session))activeBySpace.delete(session.space);return job;}
function settle(session:ActiveThoughtSession,now?:string){const task=performSettle(session,now);const tasks=settlingBySpace.get(session.space)??new Set<Promise<unknown>>();tasks.add(task);settlingBySpace.set(session.space,tasks);void task.finally(()=>{tasks.delete(task);if(tasks.size===0)settlingBySpace.delete(session.space)}).catch(()=>undefined);return task;}
function schedule(session:ActiveThoughtSession){const id=key(session);const old=timers.get(id);if(old)clearTimeout(old);timers.set(id,setTimeout(()=>{void settle(session).catch(()=>undefined)},10*60*1000));}

export async function recordCompanionThoughtRound(db:SQLiteDatabase,input:{space:PixorySpace;thread:AiThreadRecord;branchRouteHash:string;userMessage:AiMessageRecord;assistantMessage:AiMessageRecord;now:string}):Promise<ActiveThoughtSession|null>{if(!input.thread.roleCardId||input.userMessage.status!=='completed'||input.assistantMessage.status!=='completed')return null;const uh=messageHash(input.userMessage),ah=messageHash(input.assistantMessage);const candidates=detectThoughtEvents({userText:input.userMessage.content,assistantText:input.assistantMessage.content,userMessageVersionHash:uh,assistantMessageVersionHash:ah});if(!candidates.length)return null;const events=await thoughtRepository.recordEvents(db,{space:input.space,roleCardId:input.thread.roleCardId,threadId:input.thread.id,branchRouteHash:input.branchRouteHash,lineageVersion:input.thread.lineageVersion??0,userMessageId:input.userMessage.id,assistantMessageId:input.assistantMessage.id,userMessageVersionHash:uh,assistantMessageVersionHash:ah,candidates,now:input.now});if(!events.length)return null;const role=await aiRoleCardRepository.findById(db,input.thread.roleCardId);const roleSnapshot={name:role?.name??input.thread.title,prompt:(role?.prompt??input.thread.roleSnapshotJson).slice(0,1800)};return{space:input.space,roleCardId:input.thread.roleCardId,threadId:input.thread.id,branchRouteHash:input.branchRouteHash,lineageVersion:input.thread.lineageVersion??0,sessionKey:events[0].sessionKey,roleSnapshot}}

export function activateThoughtSession(session:ActiveThoughtSession|null):void{if(!session||suspendedSpaces.has(session.space))return;const previous=activeBySpace.get(session.space);if(previous&&key(previous)!==key(session)){void settle(previous).catch(()=>undefined);}activeBySpace.set(session.space,session);schedule(session)}
export function observeThoughtScope(space:PixorySpace,input:{roleCardId:string|null;threadId:string;branchRouteHash:string}):void{if(suspendedSpaces.has(space))return;const previous=activeBySpace.get(space);if(previous&&(previous.roleCardId!==input.roleCardId||previous.threadId!==input.threadId||previous.branchRouteHash!==input.branchRouteHash))void settle(previous).catch(()=>undefined)}
export async function settleActiveThoughtSessions(space?:PixorySpace):Promise<void>{const sessions=[...activeBySpace.values()].filter(s=>!space||s.space===space);for(const session of sessions)await settle(session);}
export async function reconcileThoughtSessions(space:PixorySpace):Promise<void>{if(suspendedSpaces.has(space))return;const sessions=await runWithDatabaseSpace(space,async db=>{const rows=await db.getAllAsync<{roleCardId:string;threadId:string;branchRouteHash:string;lineageVersion:number;sessionKey:string}>(`SELECT roleCardId,threadId,branchRouteHash,lineageVersion,sessionKey FROM companion_thought_events WHERE status='pending' GROUP BY roleCardId,threadId,branchRouteHash,lineageVersion,sessionKey`);const out:ActiveThoughtSession[]=[];for(const row of rows){const thread=await aiThreadRepository.findThreadById(db,row.threadId);if(!thread)continue;const scopes=thread.currentBranchRootMessageId&&thread.currentBranchVersionIndex!=null?await aiThreadRepository.resolveBranchLineage(db,thread.currentBranchRootMessageId,thread.currentBranchVersionIndex):[];if(hashBranchRoute(scopes)!==row.branchRouteHash)continue;out.push({...row,space,roleSnapshot:{name:thread.title,prompt:thread.roleSnapshotJson.slice(0,1800)}})}return out});if(suspendedSpaces.has(space))return;for(const session of sessions)await settle(session);}
export function resumeThoughtSessions(space:PixorySpace):void{suspendedSpaces.delete(space)}
export async function suspendThoughtSessions(space:PixorySpace):Promise<void>{suspendedSpaces.add(space);for(const [id,timer] of timers){if(id.startsWith(`${space}:`)){clearTimeout(timer);timers.delete(id)}}activeBySpace.delete(space);await Promise.allSettled([...(settlingBySpace.get(space)??[])])}
export const thoughtSessionCoordinator={activate:activateThoughtSession,observeScope:observeThoughtScope,reconcile:reconcileThoughtSessions,recordRound:recordCompanionThoughtRound,resume:resumeThoughtSessions,settleActive:settleActiveThoughtSessions,suspend:suspendThoughtSessions};
