export const metrics = {
  minTouchSize: 44,
  iconButtonSize: 48,
  chipHeight: 34,
  chipPaddingHorizontal: 12,
  cardPadding: 18,
  formFieldGap: 14,
  sectionGap: 22,
  bottomActionHeight: 52,
  bottomActionInset: 12,
  bottomTabHeight: 86,
  searchHeight: 50,
  thumbnailGap: 8,
  ipCardImageHeight: 168,
} as const;
