export const metrics = {
  minTouchSize: 44,
  iconButtonSize: 42,
  chipHeight: 32,
  chipPaddingHorizontal: 12,
  cardPadding: 18,
  formFieldGap: 14,
  sectionGap: 24,
  bottomActionHeight: 44,
  bottomActionInset: 12,
  bottomTabHeight: 74,
  searchHeight: 44,
  thumbnailGap: 8,
  ipCardImageHeight: 118,
} as const;
