export const metrics = {
  minTouchSize: 44,
  iconButtonSize: 42,
  chipHeight: 34,
  chipPaddingHorizontal: 14,
  cardPadding: 20,
  formFieldGap: 14,
  sectionGap: 20,
  bottomActionHeight: 44,
  bottomActionInset: 12,
  bottomTabHeight: 74,
  searchHeight: 46,
  thumbnailGap: 8,
  ipCardImageHeight: 118,
} as const;
