export const IP_NAME_MAX_LENGTH = 40;
export const GROUP_NAME_MAX_LENGTH = 40;
export const TAG_NAME_MAX_LENGTH = 24;
export const NOTE_MAX_LENGTH = 160;
export const DESCRIPTION_MAX_LENGTH = 160;

const MEBIBYTE = 1024 * 1024;

export const AI_CHAT_ATTACHMENT_MAX_COUNT = 8;
export const AI_CHAT_IMAGE_MAX_BYTES = 12 * MEBIBYTE;
export const AI_CHAT_DOCUMENT_MAX_BYTES = 24 * MEBIBYTE;
export const AI_CHAT_ATTACHMENT_MAX_TOTAL_BYTES = 32 * MEBIBYTE;
export const AI_CHAT_ATTACHMENT_UNKNOWN_SIZE_RESERVE_BYTES = 16 * MEBIBYTE;
export const AI_CHAT_ATTACHMENT_READ_CONCURRENCY = 2;

export const MEDIA_IMPORT_MAX_FILE_COUNT = 1000;
export const MEDIA_IMPORT_IMAGE_MAX_SINGLE_BYTES = 256 * MEBIBYTE;
export const MEDIA_IMPORT_VIDEO_MAX_SINGLE_BYTES = 20 * 1024 * MEBIBYTE;
export const MEDIA_IMPORT_MAX_TOTAL_BYTES = 32 * 1024 * MEBIBYTE;
export const MEDIA_IMPORT_UNKNOWN_SIZE_RESERVE_BYTES = 256 * MEBIBYTE;
export const MEDIA_IMPORT_MIN_FREE_STORAGE_BYTES = 512 * MEBIBYTE;
export const MEDIA_IMPORT_FILE_CONCURRENCY = 4;
