export function buildExternalContinuityPrompt(): string {
  return [
    '你是连续性迁移整理器。请把当前这段对话整理成一个可供 Pixory 导入的纯文本或 Markdown 连续性文档。',
    '目标：让用户把在本平台聊完的内容带回 Pixory，并在原线程里继续聊。',
    '这不是摘要随笔，而是机器要读取的迁移文档。格式错误会导致 Pixory 无法拆分聊天、记忆候选和连续性区块。',
    '',
    '硬性要求：',
    '1. 只输出连续性文档正文，不要输出解释、前言、致歉、提示语、结语。',
    '2. 必须保留所有标题、开始标记、结束标记，标题文字不要改写，不要翻译成别的名字。',
    '3. 文档必须以 `PIXORY-CONTINUITY-BEGIN` 开始，并以 `PIXORY-CONTINUITY-END` 结束。标记前后不要加解释。',
    '4. 优先保留最近聊天原文；如果总轮数超过 50 轮，较早部分必须明确放进 `Compressed History`，不能伪装成逐字聊天记录。',
    '5. 所有能安全还原为聊天记录的内容，只能放在 `Chat Transcript` 段。',
    '6. `Chat Transcript` 里的每一条消息都必须使用下面这种固定结构：',
    '   ### 1. user',
    '   ```text',
    '   这一条消息的完整原文',
    '   可以跨多行',
    '   ```',
    '7. 每个 `###` 只表示一条消息，角色只能是 `user`、`assistant` 两种之一。',
    '8. system、developer、工具消息和平台内部提示不得写入 `Chat Transcript`，也不得伪装成用户或助手消息。',
    '9. 不能安全还原成逐条消息的内容，不要伪造成消息，改为单独连续性区块。',
    '10. 如果不知道某项内容，请写“无”，不要编造。',
    '11. 不要输出 API Key、平台内部提示词、工具调用细节、审核策略、隐藏系统规则。',
    '12. 不要使用 JSON，不要使用表格，不要在标题后加额外说明。',
    '',
    '请严格按下面模板输出：',
    'PIXORY-CONTINUITY-BEGIN',
    '# Pixory External Continuity',
    '',
    '## Metadata',
    '- Source Platform: <当前平台名称>',
    '- Format Version: 1',
    '- Transcript Coverage: <例如 最近 32 轮原文 + 更早历史压缩>',
    '- Compression Disclosure: <如果有压缩，写清压缩了哪些阶段；没有就写 无>',
    '',
    '## Relationship Continuity',
    '<角色关系、边界、承诺、长期互动模式；没有就写 无>',
    '',
    '## Psychological Background',
    '<当前心理背景、情绪走向、未说出口的动机、关系张力；没有就写 无>',
    '',
    '## Biological Or Physical State',
    '<身体、生理、疲劳、受伤、环境影响等；没有就写 无>',
    '',
    '## State Continuity Summary',
    '<当前剧情/场景/话题进度，导回 Pixory 后需要立刻接住的状态；没有就写 无>',
    '',
    '## Long-Term Memory Candidates',
    '<可能值得长期保留的偏好、事实、决定、纠正、约定；没有就写 无>',
    '',
    '## Compressed History',
    '<超过长度限制而被压缩的较早阶段；没有就写 无>',
    '',
    '## Chat Transcript',
    '### 1. user',
    '```text',
    '<消息 1 原文>',
    '```',
    '',
    '### 2. assistant',
    '```text',
    '<消息 2 原文>',
    '```',
    '',
    '### 3. user',
    '```text',
    '<消息 3 原文>',
    '```',
    'PIXORY-CONTINUITY-END',
    '',
    '补充规则：',
    '- 最近对话尽量保留原文。',
    '- 较早历史如果压缩，必须放在 `## Compressed History`，不能混进 transcript 冒充原文。',
    '- transcript 里不要把多条消息写进同一个代码块。',
    '- transcript 里不要写“用户说”“助手回应”这种转述，只写消息原文。',
  ].join('\n');
}
