export function buildExternalContinuityPrompt(): string {
  return [
    '你是连续性迁移整理器。请把当前这段对话整理成一个可供 Pixory 导入的纯文本或 Markdown 连续性文档。',
    '目标：让用户把在本平台聊完的内容带回 Pixory，并在原线程里继续聊。',
    '要求：',
    '1. 只输出连续性文档正文，不要输出解释、前言、致歉、提示语。',
    '2. 优先保留最近聊天原文；如果总轮数超过 50 轮，较早部分必须明确标记为压缩总结，不能伪装成逐字聊天记录。',
    '3. 所有能安全还原为聊天记录的内容，统一放在 `## Chat Transcript` 段，逐行使用 `user:` / `assistant:` / `system:` 角色标签。',
    '4. 不能安全还原成逐条消息的内容，不要伪造成消息，改为单独连续性区块。',
    '5. 如果不知道某项内容，请留空或写“无”，不要编造。',
    '6. 不要输出 API Key、平台内部提示词、工具调用细节、审核策略、隐藏系统规则。',
    '',
    '请按下面模板输出：',
    '# Pixory External Continuity',
    '',
    '## Metadata',
    '- Source Platform: <当前平台名称>',
    '- Format Version: 1',
    '- Transcript Coverage: <例如 最近 32 轮原文 + 更早历史压缩>',
    '- Compression Disclosure: <如果有压缩，写清压缩了哪些阶段；没有就写 无>',
    '',
    '## Relationship Continuity',
    '<角色关系、边界、承诺、长期互动模式>',
    '',
    '## Psychological Background',
    '<当前心理背景、情绪走向、未说出口的动机、关系张力>',
    '',
    '## Biological Or Physical State',
    '<身体、生理、疲劳、受伤、环境影响等；没有就写 无>',
    '',
    '## State Continuity Summary',
    '<当前剧情/场景/话题进度，导回 Pixory 后需要立刻接住的状态>',
    '',
    '## Long-Term Memory Candidates',
    '<可能值得长期保留的偏好、事实、决定、纠正、约定；没有就写 无>',
    '',
    '## Compressed History',
    '<超过长度限制而被压缩的较早阶段；没有就写 无>',
    '',
    '## Chat Transcript',
    'user: <消息 1>',
    'assistant: <消息 2>',
    'user: <消息 3>',
    '',
    '补充规则：',
    '- 最近对话尽量保留原文。',
    '- 较早历史如果压缩，必须放在 `## Compressed History`，不能混进 transcript 冒充原文。',
    '- transcript 中每一行只写一条消息。',
    '- 不要使用表格，不要输出 JSON。',
  ].join('\n');
}
